language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hamza/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true hamza/frontend npm run test -- --coverage