language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hamza/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true hamza/frontend npm run test -- --coverage
  - echo $AWS_SECRET_KEY
  - echo $AWS_ACCESS_ID

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-565495860240"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_SECRET_KEY